language: perl

perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

# disable dependency install
install:
  - true

before_script:
  - perlbrew use $MYPV
  - sudo ./setup/build-thirdparty.sh /opt/znapzend/thirdparty
  - sudo ./setup/build-devel.sh /opt/znapzend/thirdparty

script:
  - ./configure --prefix=/opt/znapzend
  - sudo make install
  - perl -I/opt/znapzend/thirdparty/lib/perl5
        -MDevel::Cover=+ignore,thirdparty ./t/znapzend.t /opt/znapzend || test $? == 1 
  - perl -I/opt/znapzend/thirdparty/lib/perl5
        -MDevel::Cover=+ignore,thirdparty ./t/znapzendzetup.t /opt/znapzend || test $? == 1 
  - perl -I/opt/znapzend/thirdparty/lib/perl5
        -MDevel::Cover=+ignore,thirdparty ./t/znapzendztatz.t /opt/znapzend || test $? == 1 
  - perl -I/opt/znapzend/thirdparty/lib/perl5
        -MDevel::Cover=+ignore,thirdparty ./t/autoscrub.t /opt/znapzend || test $? == 1 
  - env PERL5LIB=/opt/znapzend/thirdparty/lib/perl5  /opt/znapzend/thirdparty/bin/cover -report coveralls

