name: Spell checking
on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '15 * * * *'
  workflow_dispatch:
    # Allow manually running the action, e.g. if disabled after some quietness in the source

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - name: Checkout (full-depth)
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        extra_dictionaries:
          cspell:software-terms/dict/softwareTerms.txt
          cspell:filetypes/filetypes.txt
          cspell:php/dict/php.txt
          cspell:node/dict/node.txt
          cspell:python/src/python/python-lib.txt
          # Some languages above (php, node, python)
          # are not used in this project, but common
          # terms listed in those dictionaries are
    - uses: check-spelling/check-spelling@v0.0.22
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        bucket: .github/workflows/
        project: spelling
